database:
  url: jdbc:mysql://localhost:3306/java-auth
  username: root
  password:

google:
  credentials: /home/alexandra/Desktop/personal-projects/matt/form-generator-utility/src/main/resources/notifications/credentials.json
  client:
    id: 694093944993-oo4ibpm6olghu4tq2sakhv45j4q869re.apps.googleusercontent.com
    secret: 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
    refresh-token: 1//09sFRe8nYQ1CgCgYIARAAGAkSNwF-L9Ir26jUx4MHZ79jtZno3bUCN6Ww4YlfQEDWh_qXcb-XCduh6peEqf4tozrMKjYPH3xokaQ
    token:
      url: https://accounts.google.com/o/oauth2/token

notification:
  template:
    header: /home/alexandra/Desktop/personal-projects/matt/form-generator-utility/src/main/resources/notifications/verification-head.html
    footer: /home/alexandra/Desktop/personal-projects/matt/form-generator-utility/src/main/resources/notifications/verification-tail.html

server:
  servlet:
    session:
      cookie:
        http-only: true
        secure: true