database:
  url: jdbc:mysql://localhost:3306/java-auth
  username: root
  password: root

google:
  credentials: /Users/matthewbleathman/Documents/GitHub/this/form-generator-utility/src/main/resources/notifications/credentials.json
  client:
    id: 694093944993-oo4ibpm6olghu4tq2sakhv45j4q869re.apps.googleusercontent.com
    secret: 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
    refresh-token: 1//09sFRe8nYQ1CgCgYIARAAGAkSNwF-L9Ir26jUx4MHZ79jtZno3bUCN6Ww4YlfQEDWh_qXcb-XCduh6peEqf4tozrMKjYPH3xokaQ
    token:
      url: https://accounts.google.com/o/oauth2/token

notification:
  template:
    header: /Users/matthewbleathman/Documents/GitHub/this/form-generator-utility/src/main/resources/notifications/verification-head.html
    footer: /Users/matthewbleathman/Documents/GitHub/this/form-generator-utility/src/main/resources/notifications/verification-tail.html